version: '3'

services:
    web:
        build: .
        command: python3 manage.py runserver 0.0.0.0:8000
        ports:
            - 8000:8000
        depends_on: 
            - postgres

    postgres:
        image: postgres:latest
        container_name: postgres_db
        ports:
            - 5433:5432
        environment: 
            - POSTGRES_PASSWORD=password
            - POSTGRES_USER=postgres
            - POSTGRES_DB=crud
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local